#ifndef __PIXEL_OPERATOR_8_BOLD_FONT_H__
#define __PIXEL_OPERATOR_8_BOLD_FONT_H__
extern unsigned char PixelOperator8_Bold_ttf[];
unsigned int PixelOperator8_Bold_ttf_len;
#endif //__PIXEL_OPERATOR_8_BOLD_FONT_H__