#ifndef __PIXEL_OPERATOR_HB_8_FONT_H__
#define __PIXEL_OPERATOR_HB_8_FONT_H__
#define PIXEL_OPERATOR_HB_8_TTF_BYTE_SIZE (19076)
extern const unsigned char PixelOperatorHB8_ttf[PIXEL_OPERATOR_HB_8_TTF_BYTE_SIZE];
#endif //__PIXEL_OPERATOR_HB_8_FONT_H__ 
